### ISSUE TITLE
tool: building `tool/xkb2ifcfg` fails after `Xml_generator` API changes

### ISSUE THREAD

**Issue by tickzip** [genodelabs/genode#5868]
The `tool/xkb2ifcfg` build has been broken since API changes introduced in https://github.com/genodelabs/genode/commit/5703f11f8e684f5c614b8eecaead2c81906bf356. The following error messages are produced when building:
```
main.cc: In member function 'void Expanding_xml_buffer::generate(const char*, const FUNC&)':
main.cc:77:54: error: 'Buffer_exceeded' is not a member of 'Genode::Xml_generator'
   77 |                         Genode::retry<Xml_generator::Buffer_exceeded>(
      |                                                      ^~~~~~~~~~~~~~~
main.cc: In instantiation of 'void Expanding_xml_buffer::generate(const char*, const FUNC&) [with FUNC = Main::_generate()::<lambda(Genode::Xml_generator&)>]':
main.cc:770:21:   required from here
main.cc:79:55: error: 'Genode::Xml_generator::Xml_generator(char*, Genode::size_t, const char*, const auto:70&) [with auto:70 = Expanding_xml_buffer::generate<Main::_generate()::<lambda(Genode::Xml_generator&)> >(const char*, const Main::_generate()::<lambda(Genode::Xml_generator&)>&)::<lambda()>::<lambda()>; Genode::size_t = long unsigned int]' is private within this context
   79 |                                         Xml_generator xml(_buffer, _buffer_size,
      |                                                       ^~~
In file included from main.cc:24:
/genode/repos/base/include/util/xml_generator.h:333:17: note: declared private here
  333 |                 Xml_generator(char *dst, size_t dst_len, char const *name, auto const &fn)
      |                 ^~~~~~~~~~~~~
make: *** [Makefile:33: xkb2ifcfg] Error 1
make: Leaving directory '/genode/tool/xkb2ifcfg'
```

**Comment by chelmuth** [comment]
Thanks for reporting! Commit 52da4d94d538323a7fa3b5f013d61ca092e20c27 fixes the obvious compiler error but the tool has still to be adapted to the `Generator` and enabled to generate HID (and optionally XML) in a follow-up.
