### ISSUE TITLE
base-fiasco: bootstrap does not build on Ubuntu 12.04 64bit

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#946]
On my machine `make VERBOSE= bootstrap` aborts with

```
  ==> Linking bootstrap
LD_PRELOAD=/plain/krishna/build/genode.fiasco_x86/l4/tool/gendep/libgendep.so GENDEP_TARGET=bootstrap GENDEP_BINARY=  GENDEP_BINARY_ALT1=ld /usr/local/genode-gcc/bin/genode-x86-ld -m elf_i386 -o bootstrap  exec.o module.o patch.o crt0.o region.o startup.o init_kip_v2.o init_kip_v4.o libc_support+.o serial.o base_critical.o support_x86.o -melf_i386 -Ttext=0x2d0000 --hash-style=sysv  -L/plain/krishna/build/genode.fiasco_x86/l4/lib/x86_586 -L/plain/krishna/build/genode.fiasco_x86/l4/lib -L/home/drops/lib/x86_586 -L/home/drops/lib  -Tbootstrap.ld   -lcxx_base -lcxx_io -nostdlib  -ll4util -luc_c /usr/lib/gcc/x86_64-linux-gnu/4.7/libgcc.a -Ttext=0x2d0000 --warn-common 
/plain/krishna/build/genode.fiasco_x86/l4/lib/x86_586/libcxx_io.a(iob_write.o): In function `L4::IOBackend::write(long long, int)':
/plain/krishna/src/genode/genode.git/base-fiasco/contrib/fiasco/snapshot/l4/pkg/cxx/lib/io/src/iob_write.cc:37: undefined reference to `__moddi3'
/plain/krishna/src/genode/genode.git/base-fiasco/contrib/fiasco/snapshot/l4/pkg/cxx/lib/io/src/iob_write.cc:38: undefined reference to `__divdi3'
/plain/krishna/build/genode.fiasco_x86/l4/lib/x86_586/libcxx_io.a(iob_write.o): In function `L4::IOBackend::write(unsigned long long, int)':
/plain/krishna/src/genode/genode.git/base-fiasco/contrib/fiasco/snapshot/l4/pkg/cxx/lib/io/src/iob_write.cc:55: undefined reference to `__umoddi3'
/plain/krishna/src/genode/genode.git/base-fiasco/contrib/fiasco/snapshot/l4/pkg/cxx/lib/io/src/iob_write.cc:56: undefined reference to `__udivdi3'
/plain/krishna/build/genode.fiasco_x86/l4/lib/x86_586/libcxx_io.a(iob_write.o): In function `L4::IOBackend::write(unsigned long long, unsigned char, unsigned char, char)':
/plain/krishna/src/genode/genode.git/base-fiasco/contrib/fiasco/snapshot/l4/pkg/cxx/lib/io/src/iob_write.cc:72: undefined reference to `__umoddi3'
/plain/krishna/src/genode/genode.git/base-fiasco/contrib/fiasco/snapshot/l4/pkg/cxx/lib/io/src/iob_write.cc:73: undefined reference to `__udivdi3'
```

The reason is that the build incorrectly tries to link `/usr/lib/gcc/x86_64-linux-gnu/4.7/libgcc.a` (which is x86_64) to `bootstrap` (which is x86_32).

This issue is related to #490.
